Enhance CI workflow with JavaScript and Ruby testing (#95)
* Enhance CI workflow with JavaScript and Ruby testing

- Added a new job for JavaScript linting and formatting checks using Prettier and ESLint.
- Introduced a test job that sets up Node.js and Ruby environments, installs dependencies, and runs Rails tests.
- Included steps to keep screenshots from failed system tests for easier debugging.

* Fixed lint CI

* Updated package-lock.json

* Run npm run check

> check
> tsc -p tsconfig.app.json && tsc -p tsconfig.node.json

error TS18003: No inputs were found in config file '/home/runner/work/shore/shore/tsconfig.app.json'. Specified 'include' paths were '["app/frontend"]' and 'exclude' paths were '[]'

* Update TypeScript configuration and add application entry point

- Changed the TypeScript configuration to include 'vite.config.ts' instead of 'vite.config.mts'.
- Added a new TypeScript entry point file for Vite integration in the Rails application, providing setup instructions and examples for loading libraries and stylesheets.

* Update ESLint configuration and remove TypeScript ESLint plugin

- Changed the import statement for the TypeScript ESLint plugin to use 'typescript-eslint'.
- Removed the '@typescript-eslint/eslint-plugin' dependency from package.json and package-lock.json.

---------

Co-authored-by: Existing User <existing@example.com>